[package]
name = "snap"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorgrad = "0.6.2"
fast_hilbert = "2.0.0"
flate2 = "1.0.22"
glob = "0.3.0"
image = "0.24.5"
libc = "0.2.133"
procfs = { path = "procfs" }
#procfs = "*"
rand = "0.8.5"
regex = "1.5.4"
tar = "0.4.37"
